name: Run Postman API Collection

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'   # Runs every day at 9 AM Nigeria time
    - cron: '0 11 * * *'  # 12 PM Nigeria time
    - cron: '0 17 * * *'  # 6 PM Nigeria time

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Install Newman locally
        run: npm install newman newman-reporter-htmlextra --save-dev

      - name: Create reports folder
        run: mkdir -p ./reports

      - name: Run gbp automation Collection
        run: npx newman run GBP_Automation.postman_collection.json --env-var BaseUrl=https://dev.dpp.prunepayments.con --env-var transaction_Id=17440c6d-26-4939-a139-a1b94740595b --env-var Account_Id=ab5daea1-c298-4acb-8d14

      - name: Upload HTML Report
        uses: actions/upload-artifact@v5
        with:
          name: newman-report
          path: ./reports/report.html
